### ISSUE TITLE
base is rotated when imported from moon

### ISSUE THREAD

**Issue by karimatrix** [djmonkeyuk/nms-base-builder#42]
if you import a base you build on moon, it is rotated for some reason, tilted at angle.

**Comment by Novoca1n3** [comment]
I haven't experienced this and have 3 bases on 3 different moons

**Comment by charliebanks** [comment]
I have experienced it when building on those floating pieces of land. Unfortunately there's not a lot I can do there as it's just the way NMS orients that bit of land. I can't guarantee that any offset I apply would fix all case scenarios. You might just need to rotate everything yourself temporarily and then move it back into place when finished.

**Comment by bjj** [comment]
My current (first blender based) base is rotated by about 1 degree, which is making me sad.

I'm sure the issue has something to do with the fact that the `BASE_FLAG` `"Up"` vector is *not* `Y=1`. In my case it looks like this:

```
        {
            "ObjectID": "^BASE_FLAG",
            "Position": [
                -0.000732421875,
                -0.0009765600552782416,
                0.0009765649447217584
            ],
            "Up": [
                0.03144059702754021,
                0.9995055198669434,
                -2.500970140317804e-06
            ],
            "At": [
                8.990947431009033e-10,
                2.5021784040291095e-06,
                0.9999997615814209
            ],
            "Timestamp": 1601273561,
            "UserData": 14
        },
```

Probably the best way to handle this in blender is to undo that Up rotation on load (and possibly the `"At"`, since it's not `Z=1` in my example) and then put them back on export so you can edit with nice coordinates but it goes back into NMS correctly

(I can confirm that if I build in-game in my base the in-game things are tilted. And the horizontal surfaces are slightly out of alignment with my viewport in-game)

**Comment by bjj** [comment]
Follow up: I ended up building mostly in Z-up space and living with a few degrees of tilt, and then did a single correction of all the objects I built in blender toward the end (and when I know more about using different transform orientations in Blender).

It turns out that the tilt varies slightly everywhere (at least on my moon) so it's not perfect, but correcting to match one object near the center of my base was enough for me.

A base on a large-ish planet has naturally built objects close to Z-up over nearly 1000u
