### ISSUE TITLE
"Connect" Update Suggestion

### ISSUE THREAD

**Issue by laanp** [djmonkeyuk/nms-base-builder#49]
How difficult would it be to code a  Optionbutton item with the Connect Button (as per attached image) to switch the python script to change the connection between 2 objects from electrical wire, to Teleport Wire, to Pipe?
The script would adjust the ObjectID to U_POWERLINE, or U_PORTALLINE to U_PIPELINE
![Connect Options](https://user-images.githubusercontent.com/72280606/94971044-d93cca00-04ba-11eb-9fcc-94149ca2f477.jpg)

**Comment by bjj** [comment]
Pretty sure right now it makes the last type of LINE that was constructed. So deselect everything, build a PORTALLINE (at the origin), delete it, select two teleporters, CONNECT. Then be sure you make a POWERLINE or you will accidentally wire everything with portals

Related:

* Only connect portallines to the portal ports (not based on proximity. Also this is hard to fix if there's already power because it merges the lightning bolt handles so the snap "next" doesn't help)
* Draw portallines in a different color!

**Comment by djmonkeyuk** [comment]
@laanp added this suggestion here:

https://github.com/djmonkeyuk/nms-base-builder/releases/tag/v2.1.2
